version: "3.7"
services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    command: --init-file /app/db.sql
    volumes:
      - ./db.sql:/app/db.sql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  api_service:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:app
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=app
      - DATABASE_PASSWORD=app
      - DATABASE_NAME=app
      - DATABASE_PORT=3306
